language: java
jdk:
  - openjdk11
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

addons:
  sonarcloud:
    organization: "safecornerscoffee"

script:
  # the following command line builds the project, runs the tests with coverage and then execute the SonarCloud analysis
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.projectKey=safecornerscoffee_spring-boot-resurrection