spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
      show_sql: true
  h2:
    console:
      enabled: true

jwt:
  header: Authorization
  secret: c3VwZXItc2VjcmV0Cg==
  token-validiity-in-seconds: 84000

logging:
  level:
    com.safecorners.coffee: debug

