spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      format_sql: true
      show_sql: true
  h2:
    console:
      enabled: true

jwt:
  header: Authorization
  secret: and0LXN1cGVyLXNlY3JldC1rZXktand0LXN1cGVyLXNlY3JldC1rZXktand0LXN1cGVyLXNlY3JldC1rZXktand0LXN1cGVyLXNlY3JldC1rZXktand0LXN1cGVyLXNlY3JldC1rZXktand0LXN1cGVyLXNlY3JldC1rZXktand0LXN1cGVyLXNlY3JldC1rZXkK
  token-validity-in-seconds: 84000

logging:
  level:
    com.safecorners.coffee: debug

